Text-related changes from feedback during unofficial reading
mpi-forum/mem-alloc pull request #11
Opened 2023-11-09 22:29 UTC by rzambre

2023-11-10 04:53 UTC, garzaran commented
This looks fine to me.

2023-11-10 04:54 UTC, garzaran approved these changes

2023-11-10 14:03 UTC, Wee-Free-Scot requested changes
kinds -> kind for each kind
Otherwise LGTM.

2023-11-10 14:03 UTC, Wee-Free-Scot commented on mem_alloc.tex
> +\section{CUDA memory kinds}
```suggestion
\section{CUDA memory kind}
```
There is one kind (although there are several restrictors for that kind).

2023-11-10 14:03 UTC, Wee-Free-Scot commented on mem_alloc.tex
> +\section{ROCm memory kinds}
```suggestion
\section{ROCm memory kind}
```
There is one kind (although there are several restrictors for that kind).

2023-11-10 14:03 UTC, Wee-Free-Scot commented on mem_alloc.tex
> +\section{Level Zero memory kinds}
```suggestion
\section{Level Zero memory kind}
```
There is one kind (although there are several restrictors for that kind).

2023-11-10 14:16 UTC, edgargabriel approved these changes
Looks fundamentally good to me. 

Short question though: the update to the ROCm example to use MPI_Comm_get_info on MPI_COMM_WORLD instead, of MPI_INFO_ENV: shall I wait until we have an agreement on the errata, or should I go ahead and file it?

2023-11-11 22:15 UTC, merged

2023-11-11 23:49 UTC, rzambre commented
> Short question though: the update to the ROCm example to use MPI_Comm_get_info on MPI_COMM_WORLD instead, of MPI_INFO_ENV: shall I wait until we have an agreement on the errata, or should I go ahead and file it?

I think we should modify the File example to use MPI_Comm_get_info on MPI_COMM_WORLD. The change would remove the dependency on the status of the MPI_INFO_ENV errata.

2023-11-13 00:28 UTC, garzaran commented
> > Short question though: the update to the ROCm example to use MPI_Comm_get_info on MPI_COMM_WORLD instead, of MPI_INFO_ENV: shall I wait until we have an agreement on the errata, or should I go ahead and file it?
> 
> I think we should modify the File example to use MPI_Comm_get_info on MPI_COMM_WORLD. The change would remove the dependency on the status of the MPI_INFO_ENV errata.

that might be a good idea ..

2023-11-13 14:23 UTC, edgargabriel commented
done, please see https://github.com/mpi-forum/mem-alloc/pull/12