initial version of ROCm memory kind example
mpi-forum/mem-alloc pull request #3
Opened 2023-10-10 20:46 UTC by edgargabriel

use MPI I/O as an example for rocm memory kind

2023-10-10 23:56 UTC, rzambre commented
I like the usage of file.

2023-10-11 13:15 UTC, edgargabriel commented
I am wondering whether this is an example where we might not need the Allreduce to confirm whether all processes have support for this particular memory kind, since we use individual MPI_File_read. I *think* it would be ok if different processes come to different conclusions about device memory support, it would still work.

2023-10-11 18:07 UTC, Wee-Free-Scot requested changes
Code comment labels to indicate usage modes
Asserted usage to permit optimization of the operations using the MPI_File

2023-10-11 18:07 UTC, Wee-Free-Scot commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
```suggestion
    // usage mode: ASSERTED
    MPI_Info info_assert = MPI_INFO_NULL;
    MPI_Info_create(&info_assert);
    MPI_Info_set(info_assert, "mpi_assert_memory_alloc_kinds", "rocm:device");
    MPI_File_open(MPI_COMM_WORLD, "inputfile",
		  MPI_MODE_RDONLY, info_assert, &file);
```

2023-10-11 19:31 UTC, edgargabriel commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
should the info_assert contain "system, rocm:device" in this case, since we might read into regular host buffer?

2023-10-12 10:30 UTC, Wee-Free-Scot commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
Hmm, yes -- you need the `if (rocm_device_aware)` earlier. If device_aware then assert "rocm:device" else assert "system", never assert both.

2023-10-12 22:58 UTC, rzambre commented on Side-doc-HIP-example.c
> +	hipStreamSynchronize(0);
Would be better to use `hipStreamDefault` instead of `0`.

2023-10-12 23:22 UTC, rzambre commented
@edgargabriel did you have a chance to compile this sample? It will probably pick up some of the minor errors (e.g. I don't see a definition `BUFSIZE` in the current version)

2023-10-13 12:35 UTC, edgargabriel commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
honestly, I am not sure I like this. Can we leave the 'asserted' part out of this example? The fundamental information that I wanted to deliver with this code snipplet is that the user can inquire whether the MPI library is able to read directly into a GPU buffer or not. The asserted code part is supposed to give the MPI library the ability to perform additional optimization possibilities. However, a) it complicates the codes and diverts from the original intent, and b) I honestly do not see how the MPI library can get around system memory, so `system, rocm:device` would make sense, but just `rocm;device` does not in my opinion

2023-10-13 12:37 UTC, edgargabriel commented
> @edgargabriel did you have a chance to compile this sample? It will probably pick up some of the minor errors (e.g. I don't see a definition `BUFSIZE` in the current version)

no, I have not. I can do that, but most of the time the code examples in MPI standard are not full blown programs, so I am not sure to what level we want to take this.

2023-10-13 13:25 UTC, Wee-Free-Scot commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
@edgargabriel what do you mean by "how the MPI library can get around system memory"?

The implementation is *always* free to use whatever intermediate buffers (of whatever kind it chooses) that it feels like using. The requested/provided is asking "can the user pass in buffers of these kinds?" 

Thus it makes sense to request "rocm:device" only; the user intent is: I will only use buffers of kind "rocm:device", is that going to work?" -- when MPI says (only) that kind is provided, it is saying "user can pass buffers of kind rocm:device (but not of any other kind)"

I was thinking that the MPI library is more likely to be able to provide support for homogenous memory kinds: all processes in a collective passing buffers of kind "rocm:device" (and MPI knowing that) is more likely to be supported than some passing "rocm:device" and some passing "system".

Your example uses individual file read (so the implementation will probably work out fine) but, at the point when the MPI_File is created, MPI doesn't know what you will use later. A collective file write, implemented as several partial gathers into file-block sized intermediate buffers, might have problems with mixed kinds, so MPI would have to say "nope, not provided" in response to "system,rocm:device", even though it could provide "system" or provide "rocm:device".

2023-10-13 13:38 UTC, edgargabriel commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
@Wee-Free-Scot I think I still disagree :-) First of all, even `system,rocm:device` provides additional information, e.g. that no managed memory will be used. But more importantly, if this would be lets say an HDF5 file read operation, it will include reading meta-data (which will probably go into system memory), and the user-data that could go into device memory. So a scenario where a single data file is used for both system and device memory is very realistic, its why I am confused that you claim that asserting `system,rocm:device` is invalid.

2023-10-13 13:48 UTC, Wee-Free-Scot commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
To be clear, I'm not saying it's invalid.

"An HDF5 read ... some data goes into system memory ... " that is a mixed usage scenario -- not what your example does. It would need separate MPI file read operations for the different kinds of memory. The goalposts have moved.

2023-10-13 13:55 UTC, edgargabriel commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
but to return the main discussion: the original intent of the example was to inquire whether the MPI library supports reading/writing directly to/from GPU buffers. The original code did that on the file handle itself, but I understand that this is invalid in the current specification, and hence the modification to retrieve this information from MPI_INFO_ENV.  

Adding the assertion in there is an entirely different scenario, that was not the original intent of the example. I personally would still be in favor of leaving that out. But I will do at this point as the group wants, I will not die fighting this issue :-)

2023-10-13 14:11 UTC, Wee-Free-Scot commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
An example showing that the user is not required to use all three usage modes is helpful. A statement somewhere saying "without the asserted usage mode, MPI might not be able to use some optimizations" would also be helpful.

2023-10-13 14:40 UTC, edgargabriel commented on Side-doc-HIP-example.c
> +		  MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
sounds good, we can do that, either in the code or in the caption of the code sample.

2023-10-13 17:14 UTC, rzambre commented
@edgargabriel compiling and running would be to ensure that the code paths are sound in case we have missed a detail. Given that this example and others (including the one in the main doc) contains header includes, I think users will expect the example to work by just copying and pasting it.

Once the example is in its final state, I can help with performing the sanity checks as well -- I don't have access to a ROCm system, but if I replace the hip calls with cuda, I should be able to test it out 🙂

2023-10-13 19:06 UTC, edgargabriel commented
The code compiles now and runs correctly (the else part, since we do not recognize the info object yet in Open MPI). I also added a comment along the lines of what we discussed with @Wee-Free-Scot .

Please let me know if there are further comments.

2023-10-13 19:31 UTC, rzambre approved these changes
Thanks for the checks. I'll wait on an approval from @Wee-Free-Scot before merging

2023-10-14 13:04 UTC, edgargabriel commented on Side-doc-HIP-example.c
> +	hipStreamSynchronize(0);
actually, turns out this is incorrect. hipStreamDefault is not the constant for the default stream, but the constant for default stream flags (incidentally it is also zero, that's why it works). I will revert this change.

```
/** Default stream creation flags. These are used with hipStreamCreate().*/
#define hipStreamDefault  0x00
```

2023-10-16 04:16 UTC, garzaran approved these changes

2023-10-16 04:16 UTC, garzaran commented on Side-doc-HIP-example.c
> +}
I went through the code and this seems fine to me

2023-10-16 19:23 UTC, rzambre commented on Side-doc-HIP-example.c
> +	hipStreamSynchronize(0);
Thanks for catching this. The CUDA example has the same issue -- I will update it.

2023-10-16 19:26 UTC, merged

2023-10-19 16:32 UTC, rzambre commented
Moved the example to a new folder: https://github.com/mpi-forum/mem-alloc/tree/main/examples-src