Add source of CUDA example in side doc
mpi-forum/mem-alloc pull request #5
Opened 2023-10-12 23:23 UTC by rzambre

2023-10-12 23:39 UTC, rzambre commented
TODO: update the example text in the doc to reflect the changes made here.

2023-10-13 11:24 UTC, Wee-Free-Scot requested changes
Two suggested changes -- neither is essential

2023-10-13 11:24 UTC, Wee-Free-Scot commented on examples-src/mem_alloc_cuda_example.cpp
> +            "org.mpi-side-doc.mem-kind.example.system",
```suggestion
            "org.mpi-forum.side-doc.mem-alloc-kind.cuda-example.system",
```
We should make an effort to ensure all our string tags are unique.

Also, there should probably be a policy for (at least the first few pieces of) all string tags published in any MPI document that is blessed by the MPI Forum -- I'm thinking "org.mpi-forum" irrespective of which document, then "side-doc.short-name-of-doc", then "example-identifier", then "usage-descriptor"
@schulzm @wesbland

2023-10-13 11:24 UTC, Wee-Free-Scot commented on examples-src/mem_alloc_cuda_example.cpp
> +        MPI_Allreduce(MPI_IN_PLACE, &cuda_device_aware, 1, MPI_INT,
This reduction could be combined with the previous one -- create an array with two elements and reduce on that with a count of 2 instead of 1.

2023-10-13 11:24 UTC, Wee-Free-Scot commented on examples-src/mem_alloc_cuda_example.cpp
> +            "org.mpi-side-doc.mem-kind.example.cuda.managed",
```suggestion
            "org.mpi-forum.side-doc.mem-alloc-kind.cuda-example.managed",
```

2023-10-13 11:24 UTC, Wee-Free-Scot commented on examples-src/mem_alloc_cuda_example.cpp
> +                "org.mpi-side-doc.mem-kind.example.cuda.device",
```suggestion
                "org.mpi-forum.side-doc.mem-alloc-kind.cuda-example.device",
```

2023-10-13 19:25 UTC, edgargabriel approved these changes
Looks good to me

2023-10-13 19:37 UTC, rzambre commented on examples-src/mem_alloc_cuda_example.cpp
> +            "org.mpi-side-doc.mem-kind.example.system",
The suggested policy looks good to me.

2023-10-13 19:37 UTC, rzambre commented on examples-src/mem_alloc_cuda_example.cpp
> +        MPI_Allreduce(MPI_IN_PLACE, &cuda_device_aware, 1, MPI_INT,
We could. I'll keep them separate for now .

2023-10-19 16:29 UTC, merged